### ISSUE TITLE
how to connect to VPN server using command line

### ISSUE THREAD

**Issue by anilaphale** [portapps/openvpn-portable#1]
Hi,

is it possble to connect to vpn server from command line. the way we do it in linux.

eg: 
d:\portablevpn\openvpn-portable.exe myconfig.ovpn

**Comment by crazy-max** [comment]
Hi @anilaphale,

Yes you can use openvpn command line switches (https://openvpn.net/community-resources/reference-manual-for-openvpn-2-4/) through the portable wrapper.
