### ISSUE TITLE
There are no TAP-Windows adapters on this system

### ISSUE THREAD

**Issue by HorselessName** [portapps/openvpn-portable#36]
#### Steps to reproduce this issue

1. Download OpenVPN Portable
2. Configure VPN profile on config folder
3. Try to connect

#### Expected behaviour

> It should connect and return "Success"

#### Actual behaviour

> When trying to connect the log returns "There are no TAP-Windows adapters on this system"

### Configuration

** Latest release version

** Windows 10

### Logs

There are no TAP-Windows adapters on this system.

**Comment by HorselessName** [comment]
Hello. How can i add a new TAP Adapter using OpenVPN Portable?
I do not see "tapctl" tool included in this.

On installed version there is a feature called "Add a new TAP-Windows6 virtual network adapter"
How can i do this using this project?

**Comment by crazy-max** [comment]
@HorselessName This is explained in the _Dependencies_ section: https://portapps.io/app/openvpn-portable/#dependencies
