### ISSUE TITLE
reg no longer seems to be imported at runtime

### ISSUE THREAD

**Issue by rpodric** [portapps/openvpn-portable#4]
#### Steps to reproduce this issue

1. Install
2. Copy in your 'data' subdir
3. Copy in your 'reg' dir (contains OpenVPN-GUI.reg)

#### Expected behaviour

The Jan 11, 2019 build, which is the only other build I had experience with, fully imported the .reg file upon running openvpn-portable.exe.

#### Actual behaviour

In the current build, nothing subordinate to HKEY_CURRENT_USER\SOFTWARE\OpenVPN-GUI (if it exists in your .reg file, of course) is imported. Notably "configs."

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** :
2.4.8-I602 win64

**Operating system (ex. Windows 10 Pro 64 bits)** :
Win10 x64

**Winver screenshot** :
https://i.imgur.com/gfA1VLm.png (also tested 1909)

### Screenshots

https://i.imgur.com/xPlGxUH.png

### Logs

Join the log file `log\[appname]-portable.log` to this issue.

> Fri, 03 Jan 2020 15:25:47 PST INF C:/portapps_opt/gopath/pkg/mod/github.com/portapps/portapps@v1.30.0/portapps.go:109 > --------
> Fri, 03 Jan 2020 15:25:47 PST INF C:/portapps_opt/gopath/pkg/mod/github.com/portapps/portapps@v1.30.0/portapps.go:110 > Operating System: Windows 10.0.19536
> Fri, 03 Jan 2020 15:25:47 PST INF C:/portapps_opt/gopath/pkg/mod/github.com/portapps/portapps@v1.30.0/portapps.go:111 > Starting OpenVPN 2.4.8-I602-7 (portapps 1.30.0)...
> Fri, 03 Jan 2020 15:25:47 PST INF C:/portapps_opt/gopath/pkg/mod/github.com/portapps/portapps@v1.30.0/portapps.go:112 > Release date: 2019/11/06 18:14:56
> Fri, 03 Jan 2020 15:25:47 PST INF C:/portapps_opt/gopath/pkg/mod/github.com/portapps/portapps@v1.30.0/portapps.go:113 > Publisher: CrazyMax (https://github.com/portapps/openvpn-portable)
> Fri, 03 Jan 2020 15:25:47 PST INF C:/portapps_opt/gopath/pkg/mod/github.com/portapps/portapps@v1.30.0/portapps.go:114 > Root path: C:\openvpn-portable
> Fri, 03 Jan 2020 15:25:47 PST INF C:/portapps_opt/gopath/pkg/mod/github.com/portapps/portapps@v1.30.0/portapps.go:118 > Loading main configuration...
> Fri, 03 Jan 2020 15:25:47 PST INF C:/portapps_opt/gopath/pkg/mod/github.com/portapps/portapps@v1.30.0/portapps.go:129 > Configuration:
> common:
>   args: []
>   env: {}
>   app_path: ""
> 
> Fri, 03 Jan 2020 15:25:47 PST ERR C:/Users/travis/build/portapps/openvpn-portable/main.go:75 > Cannot import registry key error="ERROR: The system was unable to find the specified registry key or value., exit code 1"
> Fri, 03 Jan 2020 15:25:47 PST INF C:/portapps_opt/gopath/pkg/mod/github.com/portapps/portapps@v1.30.0/portapps.go:152 > Process: C:\openvpn-portable\app\win10\bin\openvpn-gui.exe
> Fri, 03 Jan 2020 15:25:47 PST INF C:/portapps_opt/gopath/pkg/mod/github.com/portapps/portapps@v1.30.0/portapps.go:153 > Args (config file): 
> Fri, 03 Jan 2020 15:25:47 PST INF C:/portapps_opt/gopath/pkg/mod/github.com/portapps/portapps@v1.30.0/portapps.go:154 > Args (cmd line): 
> Fri, 03 Jan 2020 15:25:47 PST INF C:/portapps_opt/gopath/pkg/mod/github.com/portapps/portapps@v1.30.0/portapps.go:155 > Args (hardcoded): --exe_path C:\openvpn-portable\app\win10\bin\openvpn.exe --config_dir C:\openvpn-portable\data\config --ext_string ovpn --log_dir C:\openvpn-portable\data\log --priority_string NORMAL_PRIORITY_CLASS --append_string 0
> Fri, 03 Jan 2020 15:25:47 PST INF C:/portapps_opt/gopath/pkg/mod/github.com/portapps/portapps@v1.30.0/portapps.go:156 > Working dir: C:\openvpn-portable\app
> Fri, 03 Jan 2020 15:25:47 PST INF C:/portapps_opt/gopath/pkg/mod/github.com/portapps/portapps@v1.30.0/portapps.go:157 > App path: C:\openvpn-portable\app
> Fri, 03 Jan 2020 15:25:47 PST INF C:/portapps_opt/gopath/pkg/mod/github.com/portapps/portapps@v1.30.0/portapps.go:158 > Data path: C:\openvpn-portable\data
> Fri, 03 Jan 2020 15:25:47 PST INF C:/portapps_opt/gopath/pkg/mod/github.com/portapps/portapps@v1.30.0/portapps.go:171 > Launching OpenVPN...
> Fri, 03 Jan 2020 15:25:47 PST INF C:/portapps_opt/gopath/pkg/mod/github.com/portapps/portapps@v1.30.0/portapps.go:179 > Exec C:\openvpn-portable\app\win10\bin\openvpn-gui.exe --exe_path C:\openvpn-portable\app\win10\bin\openvpn.exe --config_dir C:\openvpn-portable\data\config --ext_string ovpn --log_dir C:\openvpn-portable\data\log --priority_string NORMAL_PRIORITY_CLASS --append_string 0

**Comment by crazy-max** [comment]
@rpodric Should be fixed with latest release: https://portapps.io/app/openvpn-portable/#download
